config:
  EVACUABLE_TAG: "evacuable"
  TAGGED_IMAGES: "true"
  TAGGED_FLAVORS: "true"
  TAGGED_AGGREGATES: "true"
  SMART_EVACUATION: "false"
  DELTA: "30"
  DELAY: "0"
  POLL: "45"
  THRESHOLD: "50"
  WORKERS: "4"
  RESERVED_HOSTS: "false"
  FORCE_RESERVED_HOST_EVACUATION: "false"
  LEAVE_DISABLED: "false"
  CHECK_KDUMP: "false"
  FENCING_TIMEOUT: "30"
  LOGLEVEL: "info"
  DISABLED: "false"
