---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-client-openstack-org-v1beta1-instanceha
  failurePolicy: Fail
  name: minstanceha.kb.io
  rules:
  - apiGroups:
    - client.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - instancehas
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-memcached-openstack-org-v1beta1-memcached
  failurePolicy: Fail
  name: mmemcached.kb.io
  rules:
  - apiGroups:
    - memcached.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - memcacheds
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-network-openstack-org-v1beta1-dnsmasq
  failurePolicy: Fail
  name: mdnsmasq.kb.io
  rules:
  - apiGroups:
    - network.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dnsmasqs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-network-openstack-org-v1beta1-ipset
  failurePolicy: Fail
  name: mipset.kb.io
  rules:
  - apiGroups:
    - network.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ipsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-network-openstack-org-v1beta1-netconfig
  failurePolicy: Fail
  name: mnetconfig.kb.io
  rules:
  - apiGroups:
    - network.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - netconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-network-openstack-org-v1beta1-reservation
  failurePolicy: Fail
  name: mreservation.kb.io
  rules:
  - apiGroups:
    - network.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - reservations
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-client-openstack-org-v1beta1-instanceha
  failurePolicy: Fail
  name: vinstanceha.kb.io
  rules:
  - apiGroups:
    - client.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - instancehas
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-memcached-openstack-org-v1beta1-memcached
  failurePolicy: Fail
  name: vmemcached.kb.io
  rules:
  - apiGroups:
    - memcached.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - memcacheds
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-network-openstack-org-v1beta1-dnsmasq
  failurePolicy: Fail
  name: vdnsmasq.kb.io
  rules:
  - apiGroups:
    - network.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dnsmasqs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-network-openstack-org-v1beta1-ipset
  failurePolicy: Fail
  name: vipset.kb.io
  rules:
  - apiGroups:
    - network.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ipsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-network-openstack-org-v1beta1-netconfig
  failurePolicy: Fail
  name: vnetconfig.kb.io
  rules:
  - apiGroups:
    - network.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - netconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-network-openstack-org-v1beta1-reservation
  failurePolicy: Fail
  name: vreservation.kb.io
  rules:
  - apiGroups:
    - network.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - reservations
  sideEffects: None
