---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-instanceha-openstack-org-v1beta1-instanceha
  failurePolicy: Fail
  name: minstanceha-v1beta1.kb.io
  rules:
  - apiGroups:
    - instanceha.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - instancehas
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-memcached-openstack-org-v1beta1-memcached
  failurePolicy: Fail
  name: mmemcached-v1beta1.kb.io
  rules:
  - apiGroups:
    - memcached.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - memcacheds
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-network-openstack-org-v1beta1-dnsmasq
  failurePolicy: Fail
  name: mdnsmasq-v1beta1.kb.io
  rules:
  - apiGroups:
    - network.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dnsmasqs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-network-openstack-org-v1beta1-ipset
  failurePolicy: Fail
  name: mipset-v1beta1.kb.io
  rules:
  - apiGroups:
    - network.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ipsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-network-openstack-org-v1beta1-netconfig
  failurePolicy: Fail
  name: mnetconfig-v1beta1.kb.io
  rules:
  - apiGroups:
    - network.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - netconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-network-openstack-org-v1beta1-reservation
  failurePolicy: Fail
  name: mreservation-v1beta1.kb.io
  rules:
  - apiGroups:
    - network.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - reservations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-rabbitmq-openstack-org-v1beta1-rabbitmq
  failurePolicy: Fail
  name: mrabbitmq-v1beta1.kb.io
  rules:
  - apiGroups:
    - rabbitmq.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rabbitmqs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-redis-openstack-org-v1beta1-redis
  failurePolicy: Fail
  name: mredis-v1beta1.kb.io
  rules:
  - apiGroups:
    - redis.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - redises
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-instanceha-openstack-org-v1beta1-instanceha
  failurePolicy: Fail
  name: vinstanceha-v1beta1.kb.io
  rules:
  - apiGroups:
    - instanceha.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - instancehas
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-memcached-openstack-org-v1beta1-memcached
  failurePolicy: Fail
  name: vmemcached-v1beta1.kb.io
  rules:
  - apiGroups:
    - memcached.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - memcacheds
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-network-openstack-org-v1beta1-dnsmasq
  failurePolicy: Fail
  name: vdnsmasq-v1beta1.kb.io
  rules:
  - apiGroups:
    - network.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dnsmasqs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-network-openstack-org-v1beta1-ipset
  failurePolicy: Fail
  name: vipset-v1beta1.kb.io
  rules:
  - apiGroups:
    - network.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ipsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-network-openstack-org-v1beta1-netconfig
  failurePolicy: Fail
  name: vnetconfig-v1beta1.kb.io
  rules:
  - apiGroups:
    - network.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - netconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-network-openstack-org-v1beta1-reservation
  failurePolicy: Fail
  name: vreservation-v1beta1.kb.io
  rules:
  - apiGroups:
    - network.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - reservations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-rabbitmq-openstack-org-v1beta1-rabbitmq
  failurePolicy: Fail
  name: vrabbitmq-v1beta1.kb.io
  rules:
  - apiGroups:
    - rabbitmq.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rabbitmqs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-redis-openstack-org-v1beta1-redis
  failurePolicy: Fail
  name: vredis-v1beta1.kb.io
  rules:
  - apiGroups:
    - redis.openstack.org
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - redises
  sideEffects: None
