## Append samples you want in your CSV to this file as resources ##
resources:
- rabbitmq_v1beta1_transporturl.yaml
- memcached_v1beta1_memcached.yaml
- instanceha_v1beta1_instanceha.yaml
- redis_v1beta1_redis.yaml
- network_v1beta1_dnsmasq.yaml
- network_v1beta1_dnsdata.yaml
- network_v1beta1_netconfig.yaml
- network_v1beta1_ipset.yaml
- network_v1beta1_reservation.yaml
- network_v1beta1_bgpconfiguration.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
