apiVersion: network.openstack.org/v1beta1
kind: DNSMasq
metadata:
  name: dnsmasq
spec:
  replicas: 1
  options:
  - key: server
    values:
    - 192.168.122.1
  debug:
    service: false
  override:
    service:
      metadata:
        annotations:
          metallb.universe.tf/address-pool: ctlplane
          metallb.universe.tf/allow-shared-ip: ctlplane
          metallb.universe.tf/loadBalancerIPs: 192.168.122.80
      spec:
        type: LoadBalancer
