apiVersion: rabbitmq.openstack.org/v1beta1
kind: RabbitMQPolicy
metadata:
  name: rabbitmqpolicy-sample
spec:
  rabbitmqClusterName: rabbitmq
  vhostRef: rabbitmqvhost-sample
  name: "queue-limits"
  pattern: ".*"
  priority: 0
  applyTo: "all"
  definition:
    max-length: 10000
